Date=input("Date:")
Name=input("Name:")
Gender=input("Gender:")
Age=input("Age:")
Father=input("Father name:")
Mother=input("Mother name:")
DOB=input("DOB:")
Nationality=input("Nationality:")
Resident=input("Resident:")
Address=input("Address:")
Language=input("First Language:")
Language=input("Second Language:")
Email=input("Email:")
Number=input("Number:")
Number=input("Parent number:")

