Date=input("Date:")
Name=input("Name:")
Gender=input("Gender:")
Age=input("Age:")
Father=input("Father name:")
Mother=input("Mother name:")
DOB=input("DOB:")
Nationality=input("Nationality:")
Resident=input("Resident:")
Address=input("Address:")
Language_F=input("First Language:")
Language_S=input("Second Language:")
Email=input("Email:")
Number_1=input("Number:")
Number_2=input("Parent number:")
print("User Info;")
print("The current date is", Date)
print("Name:", Name)
print("Gender:", Gender)
print("Age:", Age)
print("Fater name:", Father)
print("Mother name:", Mother)
print("Date of birth:", DOB)
print("Nationality:", Nationality)
print("Resident:", Resident)
print("Address:", Address)
print("First language:", Language_F)
print("Second language:", Language_S)
print("Email:", Email)
print("First Number:", Number_1)
print("Second Number:", Number_2)